name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v0
    secrets: inherit
    with:
      charm-path: "charm"

  # charm-pull-request runs unit tests on python 3.8
  # Workaround to run unit-tests in python 3.12
  # Pinning runs-on to ubuntu-24.04 as ubuntu-latest
  # https://github.com/actions/runner-images/issues/10636
  unit-tests:
    name: Unit tests (python 3.12)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: cd charm && tox -e unit-tests

  static-analysis:
    name: Static analysis (lib and charm - python 3.12)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Static analysis
        run: |
          cd charm
          tox -vve static-lib-py3
          tox -vve static-charm-py3

